"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import teal
import requests

url = "https://teal-bbs.glitch.me"

# Implementing MyFrame1
class MyProject1MyFrame1( teal.MyFrame1 ):
	def __init__( self, parent ):
		teal.MyFrame1.__init__( self, parent )

	# Handlers for MyFrame1 events.
	def on_name( self, event ):
		# TODO: Implement on_name
		pass

	def on_tweet( self, event ):
		# TODO: Implement on_tweet
		pass

	def onclick_send_button( self, event ):

		def send():
			try:
				requests.post (
					url + '/post?username=' + username + "&tweet=" + tweet
				)
				self.m_tweet.Value = ""
				self.m_staticText1.SetLabelText("投稿しました！")
			except:
				self.m_staticText1.SetLabelText("送信に失敗しました...\nもう一度お試しください。")


		username = self.m_name.Value
		tweet = self.m_tweet.Value


		if username == "" or tweet == "":
			self.m_staticText1.SetLabelText("入力漏れがあります。")
			return
		else:
			send()
